# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmanager', '0002_auto_20170729_1139'),
        ('membermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurrowedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('actual_return_date', models.DateField()),
                ('book_copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmanager.BookCopy')),
                ('burrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membermanager.Member')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membermanager.Librarian')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=400)),
                ('publisher', models.CharField(max_length=200)),
                ('requested_date', models.DateField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membermanager.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanager.Book')),
                ('reserved_by', models.ManyToManyField(to='membermanager.Member')),
            ],
        ),
    ]
