# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='bookmanager.Author'),
        ),
    ]
